# Generated by Django 6.0 on 2026-01-11 14:01

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mastodon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "description",
                    models.CharField(
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        default=None,
                        related_name="mastodon",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Users",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mastodon Account",
                "verbose_name_plural": "Mastodon Accounts",
                "ordering": ["name"],
                "permissions": [
                    ("manage_accounts", "May create, modify and delete accounts")
                ],
                "default_permissions": (),
            },
        ),
    ]
