# Generated by Django 6.0 on 2026-01-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mastodon", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mastodon",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Name"),
        ),
    ]
