# Generated by Django 6.0 on 2026-01-14 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mastodon", "0002_alter_mastodon_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mastodon",
            options={
                "default_permissions": (),
                "ordering": ["name"],
                "permissions": [
                    ("manage_accounts", "May create, modify and delete accounts")
                ],
                "verbose_name": "Mastodon account",
                "verbose_name_plural": "Mastodon accounts",
            },
        ),
    ]
