[project]
name = 'gpnmgr'
version = '0.0.1'
description = 'GPN team and access management'
readme = 'README.md'
requires-python = '>=3.13'
authors = [
    { name = 'promasu' },
]
classifiers = [
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3 :: Only',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: Python :: 3.14',
]

dependencies = [
    'Django==6.0.5',
    'django-auditlog==3.4.1',
    'django-bootstrap5==26.2',
    'django-qr-code==4.2.0',
    'django-localflavor==5.0',
    'gunicorn==26.0.0',
    'psycopg2-binary==2.9.12',
    'Authlib==1.7.2',
    'requests==2.33.1',
    'python-dateutil==2.9.0.post0',
    'ldap3==2.9.1',
]

[project.optional-dependencies]
tests = [
    'coverage==7.14.0',
    'django-stubs==6.0.4',
    'mypy==2.1.0',
    'pylint==4.0.5',
    'pylint-django==2.7.0',
    'types-requests~=2.33.0',
]
docs = [
    'mkdocs==1.6.1',
    'mkdocs-material==9.7.6'
]

[project.urls]
repository = 'https://github.com/entropia/gpnmgr'

[tool.setuptools.packages.find]
where=['src']

[tool.setuptools.package-data]
gpnmgr = ['py.typed']
