# Generated by Django 6.0 on 2025-12-28 17:12

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "slug",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Abbreviation"
                    ),
                ),
                (
                    "cost_center",
                    models.CharField(
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="Cost Center",
                    ),
                ),
                (
                    "primary_contact",
                    models.CharField(
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="Primary contact",
                    ),
                ),
                (
                    "ldap_name",
                    models.CharField(
                        default=None,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="LDAP Name",
                    ),
                ),
                (
                    "admins",
                    models.ManyToManyField(
                        default=None,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Administrators",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        default=None,
                        related_name="teams",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Members",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
                "ordering": ["slug"],
                "permissions": [
                    ("manage_teams", "May create, modify and delete teams")
                ],
                "default_permissions": (),
            },
        ),
    ]
