# Generated by Django 6.0.2 on 2026-03-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_alter_team_admins"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="visibility",
            field=models.IntegerField(
                choices=[(0, "Public"), (1, "Members only"), (2, "Admins only")],
                default=0,
                verbose_name="Visibility",
            ),
        ),
    ]
