# Generated by Django 6.0.5 on 2026-05-25 20:33

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0005_alter_accountrequest_inviter_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactDetails",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pronoun",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="pronoun"
                    ),
                ),
                (
                    "matrixHandle",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="matrixHandle",
                    ),
                ),
                (
                    "dectNumber",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="dectNumber"
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("accounts.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
