# Generated by Django 6.0 on 2026-01-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="object_dn",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="LDAP DN"
            ),
        ),
    ]
