# Generated by Django 6.0 on 2026-01-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_accountrequest"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accountrequest",
            options={
                "default_permissions": (),
                "ordering": ["-created_at"],
                "permissions": [("manage_requests", "May see and revoke requests")],
                "verbose_name": "Account request",
                "verbose_name_plural": "Account requests",
            },
        ),
        migrations.AlterField(
            model_name="accountrequest",
            name="is_revoked",
            field=models.BooleanField(default=False, verbose_name="Revocation"),
        ),
    ]
