# Generated by Django 6.0.2 on 2026-02-15 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_accountrequest_options_and_more"),
        ("teams", "0002_alter_team_admins"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountrequest",
            name="inviter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_invites",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Inviter",
            ),
        ),
        migrations.AlterField(
            model_name="accountrequest",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="member_invites",
                to="teams.team",
                verbose_name="Team",
            ),
        ),
    ]
